#!/bin/bash
# Git Memory Provider Installer for Hermes Agent
#
# Usage:
#   bash hermes/install.sh [REPO_PATH]
#
# Example:
#   bash hermes/install.sh ~/my-claw-memory

set -e

echo "🫡 Git Memory Provider for Hermes - Installer"
echo "=============================================="

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Get repo path
REPO_PATH="${1:-$HOME/my-claw-memory}"
REPO_PATH=$(eval echo "$REPO_PATH")

echo -e "${YELLOW}Repository path: ${REPO_PATH}${NC}"

# Find Hermes installation
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
HERMES_AGENT="${HERMES_AGENT:-$HOME/hermes-agent}"

if [ ! -d "$HERMES_AGENT" ]; then
    echo -e "${RED}Error: Hermes Agent not found at $HERMES_AGENT${NC}"
    echo "Please install Hermes first: curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash"
    exit 1
fi

echo -e "${GREEN}Found Hermes at $HERMES_AGENT${NC}"

# Check if repo exists and is a git repo
if [ ! -d "$REPO_PATH/.git" ]; then
    echo -e "${YELLOW}Warning: $REPO_PATH is not a git repository${NC}"
    echo "Would you like to clone or initialize it? (clone/init/skip)"
    read -r answer
    case $answer in
        clone)
            echo "Enter git remote URL (e.g., git@github.com:user/repo.git):"
            read -r remote_url
            git clone "$remote_url" "$REPO_PATH"
            ;;
        init)
            mkdir -p "$REPO_PATH"
            cd "$REPO_PATH"
            git init
            echo "Initialized empty git repository at $REPO_PATH"
            ;;
        skip)
            echo "Skipping repo setup. Please ensure it's a git repository later."
            ;;
        *)
            echo "Invalid option. Exiting."
            exit 1
            ;;
    esac
fi

# Install provider to Hermes plugins
PLUGIN_DIR="$HERMES_AGENT/plugins/memory/gitmemory"
echo -e "${YELLOW}Installing provider to $PLUGIN_DIR${NC}"

mkdir -p "$PLUGIN_DIR"
cp hermes/__init__.py "$PLUGIN_DIR/"
cp hermes/provider.py "$PLUGIN_DIR/"

echo -e "${GREEN}Provider installed${NC}"

# Update Hermes config
HERMES_CONFIG="$HERMES_HOME/config.yaml"
echo -e "${YELLOW}Updating Hermes config${NC}"

mkdir -p "$HERMES_HOME"

if [ -f "$HERMES_CONFIG" ]; then
    # Backup existing config
    cp "$HERMES_CONFIG" "$HERMES_CONFIG.backup.$(date +%Y%m%d%H%M%S)"
    
    # Use Python to update YAML properly
    python3 << PYEOF
import yaml
import os

config_path = "$HERMES_CONFIG"
repo_path = "$REPO_PATH"

with open(config_path, 'r') as f:
    config = yaml.safe_load(f) or {}

if 'memory' not in config:
    config['memory'] = {}

config['memory']['provider'] = 'gitmemory'
config['memory']['repo'] = repo_path

with open(config_path, 'w') as f:
    yaml.dump(config, f, default_flow_style=False)

print("Config updated successfully")
PYEOF
else
    # Create new config
    cat > "$HERMES_CONFIG" << YAMLEOF
# Hermes Agent Configuration
# Generated by Git Memory Provider installer

memory:
  provider: gitmemory
  repo: $REPO_PATH
  auto_commit: true
  auto_push: true
YAMLEOF
fi

echo -e "${GREEN}Config updated at $HERMES_CONFIG${NC}"

# Set environment variable (add to .bashrc if not already there)
if ! grep -q "GIT_MEMORY_REPO" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "# Git Memory Provider for Hermes" >> "$HOME/.bashrc"
    echo "export GIT_MEMORY_REPO=\"$REPO_PATH\"" >> "$HOME/.bashrc"
    echo -e "${GREEN}Added GIT_MEMORY_REPO to .bashrc${NC}"
fi

# Done
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✅ Git Memory Provider installed!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Configuration:"
echo "  - Repo: $REPO_PATH"
echo "  - Config: $HERMES_CONFIG"
echo ""
echo "Next steps:"
echo "  1. Restart Hermes: hermes gateway restart"
echo "  2. Or restart Hermes service: systemctl restart hermes-gateway"
echo "  3. Test: In Hermes chat, try 'gitmemory_status' tool"
echo ""
echo "Available tools:"
echo "  - gitmemory_status  : Check sync status"
echo "  - gitmemory_commit  : Commit memory changes"
echo "  - gitmemory_push    : Push to remote"
echo "  - gitmemory_pull    : Pull from remote"
